import type { Product, Category, ShippingMethod, Usuario, Pedido } from "../types"

// 🔹 Shipping Method
export const mockShippingMethods: ShippingMethod[] = [
  {
    id: "1",
    name: "Correo Argentino",
    eta: "",
    regions: ["Nacional"],
    priceRules: "Gratis en compras mayores a $500000",
    icon: "📦",
  },
  {
    id: "2",
    name: "Envío Express",
    eta: "",
    regions: ["Gran Mendoza"],
    priceRules: "Arreglar con el vendedor",
    icon: "⚡",
  },
  {
    id: "3",
    name: "Retiro por el local",
    eta: "",
    regions: ["Mendoza"],
    priceRules: "Gratis",
    icon: "🔒",
  },
]

// 🔹 Usuarios
export const mockUsuarios: Usuario[] = [
  {
    id: "1",
    nombre: "admin",
    email: "admin@admin.com",
    telefono: "",
    rol: "admin",
    direcciones: [],
  },
  {
    id: "2",
    nombre: "Test1",
    email: "test1@test.com",
    telefono: "",
    rol: "cliente",
    direcciones: [],
  },
  {
    id: "3",
    nombre: "rodrigo carcano",
    email: "rodrigocarcano5@gmail.com",
    telefono: "",
    rol: "cliente",
    direcciones: [],
  },
  {
    id: "4",
    nombre: "test2",
    email: "test2@test.com",
    telefono: "",
    rol: "cliente",
    direcciones: [],
  },
  {
    id: "5",
    nombre: "test3",
    email: "test3@test.com",
    telefono: "",
    rol: "cliente",
    direcciones: [],
  },
]

// 🔹 Categorías (todas las que pasaste)
export const mockCategorias = [
  { id: 38, nombre: "Lencería Erótica", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/12/mordisco.jpg" },
  { id: 43, nombre: "Afrodisíacos", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/12/Afrodisiaco-e1643659191871.jpg" },
  { id: 45, nombre: "Lubricantes", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2024/10/lubricantes.jpg" },
  { id: 47, nombre: "Anillos", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/12/Anillos-e1639632352606.jpg" },
  { id: 49, nombre: "Anales", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/12/plug-a1.jpg" },
  { id: 50, nombre: "Bolas Chinas", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2019/11/Bolas-Chinas-Juguetes-Sexuales.jpg" },
  { id: 51, nombre: "Prótesis", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/12/protesis-realisticas.jpg" },
  { id: 52, nombre: "Dildos", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2024/10/consoladores-.jpg" },
  { id: 53, nombre: "Dildos Realísticos", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2023/05/realista.jpg" },
  { id: 54, nombre: "Dildos Gigantes", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2023/05/realista-2.jpg" },
  { id: 55, nombre: "Vibradores", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/11/lovers-6.jpeg" },
  { id: 56, nombre: "Vibradores Realísticos", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2023/05/vib.realist.jpg" },
  { id: 57, nombre: "Vibradores Importados", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/11/lovers-6.jpeg" },
  { id: 59, nombre: "Masculino", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/12/Estimulador-masculino.jpg" },
  { id: 60, nombre: "Doble Penetración", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/12/Doble-penetracion.jpg" },
  { id: 61, nombre: "Fundas - Extensiones", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/11/lovers-5.jpeg" },
  { id: 64, nombre: "Accesorios", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2022/03/Accesoios.jpg" },
  { id: 65, nombre: "Sado/BDSM", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2021/12/bondage-mendoza.jpg" },
  { id: 651, nombre: "Sin categorizar", url_imagen: null },
  { id: 672, nombre: "Vibradores Comunes", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2023/05/vib-comunes.jpg" },
  { id: 675, nombre: "Dildos Comunes", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2023/05/realista-1.jpg" },
  { id: 679, nombre: "Succionadores", url_imagen: "https://loversplaysexshop.com/wp-content/uploads/2025/02/succionador.jpg" },
]

// 🔹 Productos (todos los que me pasaste)
export const mockProductos: Product[] = [
  {
    id: 145,
    nombre: "Disfraz Mujer Policía",
    precio: 42000,
    stock: 2,
    descripcion_corta: "La ley es placer, para satisfacer tus fantasías.",
    descripcion_larga: "Disfraz Mujer Policía con 6 piezas, microfibra regulable, gorro, corbata y esposas.",
    url_imagen_principal: "https://loversplaysexshop.com/wp-content/uploads/2019/10/717-Police-Girl-Disfraces-Venta-Online-Lovers-Play-Sex-Shop-Mendoza-Argentina.jpg",
    imagenes: [
      "https://loversplaysexshop.com/wp-content/uploads/2019/10/715-Police-Girl-Disfraces-Venta-Online-Lovers-Play-Sex-Shop-Mendoza-Argentina.jpg",
      "https://loversplaysexshop.com/wp-content/uploads/2019/10/716-Police-Girl-Disfraces-Venta-Online-Lovers-Play-Sex-Shop-Mendoza-Argentina.jpg",
    ],
    categoria_id: 38,
    vistas: 34,
    slug: "disfraz-mujer-policia",
  },
  {
    id: 6671,
    nombre: "PRUEBA1",
    precio: 1500,
    stock: 89,
    descripcion_corta: "Producto de prueba genérico",
    descripcion_larga: "Producto de prueba 1 sin descripción larga.",
    url_imagen_principal: "https://imgur.com/owkAYDG.jpg",
    imagenes: [],
    categoria_id: 52,
    vistas: 26,
    slug: "prueba1",
  },
  {
    id: 56,
    nombre: "Varita Anal - Simple",
    precio: 9900,
    stock: 8,
    descripcion_corta: "Dilatador Anal Inexpulsable con 10 esferas suaves.",
    descripcion_larga: "Varita Anal Simple de silicona, 25cm largo, 10 perlas, anillo de extracción.",
    url_imagen_principal: "https://loversplaysexshop.com/wp-content/uploads/2019/09/Varita-Anal-Simple-a.jpg",
    imagenes: [
      "https://loversplaysexshop.com/wp-content/uploads/2019/09/Varita-Anal-Simple-b.jpg",
      "https://loversplaysexshop.com/wp-content/uploads/2019/09/Varita-Anal-Simple-c.jpg",
    ],
    categoria_id: 49,
    vistas: 22,
    slug: "varita-anal-simple",
  },
  {
    id: 5933,
    nombre: "Profiláctico Texturado - Funda",
    precio: 3500,
    stock: 3,
    descripcion_corta: "Funda elástica de silicona suave para mayor placer y control.",
    descripcion_larga: "Funda profiláctica texturada, transparente, flexible y adaptable, 13cm x 3,5cm.",
    url_imagen_principal: "https://loversplaysexshop.com/wp-content/uploads/2024/05/Profilactico-Texturado-Funda-a.jpg",
    imagenes: [
      "https://loversplaysexshop.com/wp-content/uploads/2024/05/Profilactico-Texturado-Funda-b.jpg",
      "https://loversplaysexshop.com/wp-content/uploads/2024/05/Profilactico-Texturado-Funda-c.jpg",
    ],
    categoria_id: 61,
    vistas: 10,
    slug: "profilactico-texturado-funda",
  },
  {
    id: 26,
    nombre: "Bomba de Vacío - con Válvula",
    precio: 35000,
    stock: 2,
    descripcion_corta: "Aumenta el tamaño y grosor del pene. Combate impotencia temporal.",
    descripcion_larga: "Bomba de vacío acrílica con válvula de alivio manual. Medidas 21x6 cm.",
    url_imagen_principal: "https://loversplaysexshop.com/wp-content/uploads/2019/09/1438-Con-Valvula-Bombas-de-Vacio-Venta-Online-Lovers-Play-Sex-Shop-Mendoza-Argentina.jpg",
    imagenes: [
      "https://loversplaysexshop.com/wp-content/uploads/2019/09/1439-Con-Valvula-Bombas-de-Vacio-Venta-Online-Lovers-Play-Sex-Shop-Mendoza-Argentina.jpg",
    ],
    categoria_id: 59,
    vistas: 8,
    slug: "bomba-de-vacio-con-valvula",
  },
  {
    id: 224,
    nombre: "Tanga Less - Mordisco 001 - Negro",
    precio: 8500,
    stock: 1,
    descripcion_corta: "Tanga de microfibra Mordisco.",
    descripcion_larga: "Tanga Less modelo Mordisco 001 en color negro.",
    url_imagen_principal: "https://loversplaysexshop.com/wp-content/uploads/2019/11/Tanga-Mordisco-001-Negro-b.jpg",
    imagenes: [],
    categoria_id: 38,
    vistas: 8,
    slug: "tanga-less-mordisco-001",
  },
  {
    id: 6672,
    nombre: "PRUEBA2",
    precio: 1000,
    stock: 8,
    descripcion_corta: "Producto de prueba genérico",
    descripcion_larga: "Producto de prueba 2 sin descripción larga.",
    url_imagen_principal: "https://imgur.com/owkAYDG.jpg",
    imagenes: [],
    categoria_id: 52,
    vistas: 8,
    slug: "prueba2",
  },
  {
    id: 33,
    nombre: "Super - Consolador - Piel",
    precio: 16000,
    stock: 2,
    descripcion_corta: "Consolador piel super.",
    descripcion_larga: "Consolador de piel super realista.",
    url_imagen_principal: "https://loversplaysexshop.com/wp-content/uploads/2022/05/Super-Consolador-Piel-a.jpg",
    imagenes: [],
    categoria_id: 52,
    vistas: 4,
    slug: "super-consolador-piel",
  },
  {
    id: 48,
    nombre: "Vagina Símil  - Piel - Realistic",
    precio: 19000,
    stock: 2,
    descripcion_corta: "Estimulador masculino vagina símil piel.",
    descripcion_larga: "Vagina de silicona realista.",
    url_imagen_principal: "https://loversplaysexshop.com/wp-content/uploads/2019/09/1401-Vagina-Simil-Estimulador-Masculino-Venta-Online-Sex-Shop-Mendoza-Argentina.jpg",
    imagenes: [],
    categoria_id: 59,
    vistas: 4,
    slug: "vagina-simil-realistic",
  },
  {
    id: 64,
    nombre: "Látigo Largo - 60cm Ecocuero",
    precio: 19000,
    stock: 3,
    descripcion_corta: "Látigo largo de 60cm en ecocuero.",
    descripcion_larga: "Accesorio BDSM en ecocuero resistente.",
    url_imagen_principal: "https://loversplaysexshop.com/wp-content/uploads/2019/09/Latigo-b.jpg",
    imagenes: [],
    categoria_id: 65,
    vistas: 4,
    slug: "latigo-largo-ecocuero",
  },
]

// 🔹 Pedidos
export const mockPedidos: Pedido[] = [
  {
    id: "10",
    fecha: "2025-09-23T22:22:17.110593",
    total: 15000,
    estado: "PENDIENTE",
    items: [
      { producto: "PRUEBA1", cantidad: 10, subtotal: 15000 },
    ],
  },
  {
    id: "11",
    fecha: "2025-09-23T23:55:04.544484",
    total: 3500,
    estado: "PENDIENTE",
    items: [
      { producto: "PRUEBA2", cantidad: 2, subtotal: 2000 },
      { producto: "PRUEBA1", cantidad: 1, subtotal: 1500 },
    ],
  },
]


